version: "3.9"
services:
  tau:
    build: .
    ports:
      - "8080:8080"
    privileged: true
    devices:
      - '/dev:/dev'
    volumes:
      - type: bind
        source: ./measurements
        target: /app/measurements
        bind:
          create_host_path: true
    restart: always
  rate_limiter:
    build: rate_limiter/.
    restart: always
    privileged: true
    devices:
      - '/dev:/dev'